baseurl = "/"
languageCode = "en-us"
title = "Sivel.net"
theme = "sivelnet"
metaDataFormat = "yaml"

[pagination]
  pagerSize = 10

[permalinks]
  post = "/:year/:month/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Throwing Hot Coals"
  DateFormat = "January 02, 2006"
  googleAnalytics = "UA-3706980-1"
  disqus = "sivel"
